python scripts/train4.py --mode teacher --teacher_type MLP --age_threshold 65 --data_dir ./data/ad;python scripts/train4.py --mode student --teacher_type MLP --student_type MLP --teacher_model_path ./experiments/ad_teacher_MLP_age65_es20_run1/teacher_run_1.pth --age_threshold 65 --data_dir ./data/ad;
python scripts/train4.py --mode teacher --teacher_type AgeAwareMLP1 --age_threshold 65 --data_dir ./data/ad;python scripts/train4.py --mode student --teacher_type AgeAwareMLP1 --student_type AgeAwareMLP1 --teacher_model_path ./experiments/ad_teacher_AgeAwareMLP1_age65_es20_run1/teacher_run_1.pth --age_threshold 65 --data_dir ./data/ad;python scripts/train4.py --mode student --teacher_type AgeAwareMLP1 --student_type MLP --teacher_model_path ./experiments/ad_teacher_AgeAwareMLP1_age65_es20_run1/teacher_run_1.pth --age_threshold 65 --data_dir ./data/ad;
python scripts/train4.py --mode teacher --teacher_type AgeAwareMLP2 --age_threshold 65 --data_dir ./data/ad;python scripts/train4.py --mode student --teacher_type AgeAwareMLP2 --student_type AgeAwareMLP2 --teacher_model_path ./experiments/ad_teacher_AgeAwareMLP2_age65_es20_run1/teacher_run_1.pth --age_threshold 65 --data_dir ./data/ad;python scripts/train4.py --mode student --teacher_type AgeAwareMLP2 --student_type MLP --teacher_model_path ./experiments/ad_teacher_AgeAwareMLP2_age65_es20_run1/teacher_run_1.pth --age_threshold 65 --data_dir ./data/ad;

python scripts/train4.py --mode teacher --teacher_type MLP --age_threshold 65 --data_dir ./data/ms;python scripts/train4.py --mode student --teacher_type MLP --student_type MLP --teacher_model_path ./experiments/ms_teacher_MLP_age65_es20_run1/teacher_run_1.pth --age_threshold 65 --data_dir ./data/ms;
python scripts/train4.py --mode teacher --teacher_type AgeAwareMLP1 --age_threshold 65 --data_dir ./data/ms;python scripts/train4.py --mode student --teacher_type AgeAwareMLP1 --student_type AgeAwareMLP1 --teacher_model_path ./experiments/ms_teacher_AgeAwareMLP1_age65_es20_run1/teacher_run_1.pth --age_threshold 65 --data_dir ./data/ms;python scripts/train4.py --mode student --teacher_type AgeAwareMLP1 --student_type MLP --teacher_model_path ./experiments/ms_teacher_AgeAwareMLP1_age65_es20_run1/teacher_run_1.pth --age_threshold 65 --data_dir ./data/ms;
python scripts/train4.py --mode teacher --teacher_type AgeAwareMLP2 --age_threshold 65 --data_dir ./data/ms;python scripts/train4.py --mode student --teacher_type AgeAwareMLP2 --student_type AgeAwareMLP2 --teacher_model_path ./experiments/ms_teacher_AgeAwareMLP2_age65_es20_run1/teacher_run_1.pth --age_threshold 65 --data_dir ./data/ms;python scripts/train4.py --mode student --teacher_type AgeAwareMLP2 --student_type MLP --teacher_model_path ./experiments/ms_teacher_AgeAwareMLP2_age65_es20_run1/teacher_run_1.pth --age_threshold 65 --data_dir ./data/ms;

python scripts/train4.py --mode teacher --teacher_type MLP --age_threshold 65 --data_dir ./data/uc;python scripts/train4.py --mode student --teacher_type MLP --student_type MLP --teacher_model_path ./experiments/uc_teacher_MLP_age65_es20_run1/teacher_run_1.pth --age_threshold 65 --data_dir ./data/uc;
python scripts/train4.py --mode teacher --teacher_type AgeAwareMLP1 --age_threshold 65 --data_dir ./data/uc;python scripts/train4.py --mode student --teacher_type AgeAwareMLP1 --student_type AgeAwareMLP1 --teacher_model_path ./experiments/uc_teacher_AgeAwareMLP1_age65_es20_run1/teacher_run_1.pth --age_threshold 65 --data_dir ./data/uc;python scripts/train4.py --mode student --teacher_type AgeAwareMLP1 --student_type MLP --teacher_model_path ./experiments/uc_teacher_AgeAwareMLP1_age65_es20_run1/teacher_run_1.pth --age_threshold 65 --data_dir ./data/uc;
python scripts/train4.py --mode teacher --teacher_type AgeAwareMLP2 --age_threshold 65 --data_dir ./data/uc;python scripts/train4.py --mode student --teacher_type AgeAwareMLP2 --student_type AgeAwareMLP2 --teacher_model_path ./experiments/uc_teacher_AgeAwareMLP2_age65_es20_run1/teacher_run_1.pth --age_threshold 65 --data_dir ./data/uc;python scripts/train4.py --mode student --teacher_type AgeAwareMLP2 --student_type MLP --teacher_model_path ./experiments/uc_teacher_AgeAwareMLP2_age65_es20_run1/teacher_run_1.pth --age_threshold 65 --data_dir ./data/uc;python src/analyze_age_matrix_2.py


